import { Exam } from '@/interfaces/exams-interfaces';

export const mockExams: Exam[] = [
  {
    id: '1',
    title: 'Estructura Atómica',
    category: 'Quimica',
    group: 'PRIMERO',
    questions: [
      {
        id: '1',
        text: '¿Qué partículas subatómicas componen un átomo?',
        options: [
          'Protones, neutrones y electrones',
          'Fotones y neutrones',
          'Electrones y protones únicamente',
          'Protones y fotones',
        ],
        correctAnswer: 0,
      },
      {
        id: '2',
        text: '¿Qué es el número atómico?',
        options: [
          'El número de protones en un átomo',
          'El número de electrones en un átomo',
          'La masa del átomo',
          'El número de neutrones en un átomo',
        ],
        correctAnswer: 0,
      },
      // ... (rest of the questions)
    ],
    createdAt: new Date('2024-03-12'),
  },
  {
    id: '2',
    title: 'Reacciones Químicas Básicas',
    category: 'Quimica',
    group: 'SEGUNDO',
    questions: [
      // ... (questions)
    ],
    createdAt: new Date('2024-03-13'),
  },
  {
    id: '3',
    title: 'Nomenclatura Química Orgánica',
    category: 'Quimica',
    group: 'TERCERO',
    questions: [
      // ... (questions)
    ],
    createdAt: new Date('2024-03-14'),
  },
  {
    id: '4',
    title: 'Química de Medicamentos',
    category: 'Farmacia',
    group: 'CUARTO',
    questions: [
      // ... (questions)
    ],
    createdAt: new Date('2024-03-20'),
  },
  // Nuevo examen de Química para CUARTO
  {
    id: '5',
    title: 'Química Analítica Avanzada',
    category: 'Quimica',
    group: 'CUARTO',
    questions: [
      {
        id: '1',
        text: '¿Qué técnica se utiliza para separar mezclas basándose en la velocidad de migración de sus componentes en un campo eléctrico?',
        options: [
          'Electroforesis',
          'Cromatografía',
          'Espectroscopía',
          'Titulación',
        ],
        correctAnswer: 0,
      },
      {
        id: '2',
        text: 'En la espectroscopía UV-Vis, ¿qué se mide principalmente?',
        options: [
          'La absorción de luz en función de la longitud de onda',
          'La emisión de partículas alfa',
          'La refracción de la luz',
          'La conductividad eléctrica',
        ],
        correctAnswer: 0,
      },
      {
        id: '3',
        text: '¿Qué es la cromatografía de gases?',
        options: [
          'Una técnica para separar compuestos volátiles',
          'Un método para medir pH',
          'Una técnica para determinar masas moleculares',
          'Un tipo de reacción química',
        ],
        correctAnswer: 0,
      },
      {
        id: '4',
        text: '¿Cuál es el principio básico de la titulación ácido-base?',
        options: [
          'Neutralización',
          'Oxidación',
          'Precipitación',
          'Reducción',
        ],
        correctAnswer: 0,
      },
      {
        id: '5',
        text: 'En una solución buffer, ¿qué sucede al agregar pequeñas cantidades de ácido o base?',
        options: [
          'El pH se mantiene casi constante',
          'El pH aumenta drásticamente',
          'La solución se vuelve sólida',
          'El pH disminuye drásticamente',
        ],
        correctAnswer: 0,
      },
      {
        id: '6',
        text: '¿Qué detector se utiliza comúnmente en HPLC?',
        options: [
          'Detector de índice de refracción',
          'Espectrómetro de masas',
          'Detector de rayos X',
          'Espectrofotómetro UV-Vis',
        ],
        correctAnswer: 3,
      },
      {
        id: '7',
        text: '¿Qué representa el término "fase estacionaria" en cromatografía?',
        options: [
          'El material sólido o líquido inmóvil en la columna',
          'El solvente que fluye a través de la columna',
          'El analito que se está separando',
          'El detector usado para medir',
        ],
        correctAnswer: 0,
      },
      {
        id: '8',
        text: '¿Cuál es el objetivo principal de la espectroscopía de infrarrojo?',
        options: [
          'Identificar grupos funcionales en moléculas orgánicas',
          'Medir emisiones nucleares',
          'Determinar la concentración de iones metálicos',
          'Analizar estructuras cristalinas',
        ],
        correctAnswer: 0,
      },
      {
        id: '9',
        text: 'En la valoración redox, ¿qué tipo de reacción química es fundamental?',
        options: [
          'Transferencia de electrones',
          'Formación de sales',
          'Intercambio de protones',
          'Reacciones de combustión',
        ],
        correctAnswer: 0,
      },
      {
        id: '10',
        text: '¿Qué es la polarografía?',
        options: [
          'Una técnica electroquímica para analizar metales pesados',
          'Un método de separación de mezclas',
          'Una técnica para medir la presión osmótica',
          'Un tipo de espectroscopía',
        ],
        correctAnswer: 0,
      },
    ],
    createdAt: new Date('2024-03-21'),
  },
  // Exámenes de Farmacia para PRIMERO, SEGUNDO y TERCERO
  {
    id: '6',
    title: 'Introducción a la Farmacia',
    category: 'Farmacia',
    group: 'PRIMERO',
    questions: [
      {
        id: '1',
        text: '¿Qué es la farmacognosia?',
        options: [
          'El estudio de medicamentos de origen natural',
          'El estudio de los efectos de los fármacos en el cuerpo',
          'La síntesis química de nuevos medicamentos',
          'La distribución de medicamentos',
        ],
        correctAnswer: 0,
      },
      {
        id: '2',
        text: '¿Qué es una forma farmacéutica sólida?',
        options: [
          'Tabletas y cápsulas',
          'Jarabes',
          'Emulsiones',
          'Inhaladores',
        ],
        correctAnswer: 0,
      },
      {
        id: '3',
        text: '¿Cuál es la principal función de un farmacéutico?',
        options: [
          'Dispensar medicamentos y asesorar a los pacientes',
          'Realizar cirugías menores',
          'Diagnosticar enfermedades',
          'Dirigir campañas de salud pública',
        ],
        correctAnswer: 0,
      },
      {
        id: '4',
        text: '¿Qué es la farmacología?',
        options: [
          'La ciencia que estudia las propiedades de los fármacos y sus acciones',
          'El estudio de la genética humana',
          'La producción industrial de medicamentos',
          'La distribución logística de productos farmacéuticos',
        ],
        correctAnswer: 0,
      },
      {
        id: '5',
        text: '¿Qué regula la farmacopea?',
        options: [
          'Los estándares de calidad de los medicamentos',
          'Los precios de los medicamentos',
          'Las prácticas de marketing farmacéutico',
          'La formación académica de los farmacéuticos',
        ],
        correctAnswer: 0,
      },
      {
        id: '6',
        text: '¿Qué es un medicamento genérico?',
        options: [
          'Un medicamento equivalente al de marca en dosis y eficacia',
          'Un medicamento de marca reconocido',
          'Un suplemento dietético',
          'Un medicamento experimental',
        ],
        correctAnswer: 0,
      },
      {
        id: '7',
        text: '¿Qué significa OTC en farmacia?',
        options: [
          'Medicamentos de venta libre sin receta',
          'Medicamentos controlados',
          'Medicamentos de alto costo',
          'Productos cosméticos',
        ],
        correctAnswer: 0,
      },
      {
        id: '8',
        text: '¿Cuál es el papel de la Agencia Europea de Medicamentos (EMA)?',
        options: [
          'Evaluar y supervisar medicamentos en la Unión Europea',
          'Distribuir medicamentos a las farmacias',
          'Regular los precios de los medicamentos',
          'Investigar nuevas enfermedades',
        ],
        correctAnswer: 0,
      },
      {
        id: '9',
        text: '¿Qué es una receta magistral?',
        options: [
          'Un medicamento preparado individualmente según prescripción',
          'Un medicamento producido en masa',
          'Un suplemento alimenticio',
          'Una receta para medicamentos OTC',
        ],
        correctAnswer: 0,
      },
      {
        id: '10',
        text: '¿Qué es la bioequivalencia?',
        options: [
          'Cuando dos medicamentos tienen la misma biodisponibilidad y efecto',
          'La equivalencia química entre dos sustancias',
          'La comparación entre un medicamento y un alimento',
          'La relación entre dosis y peso corporal',
        ],
        correctAnswer: 0,
      },
    ],
    createdAt: new Date('2024-03-15'),
  },
  {
    id: '7',
    title: 'Farmacología General',
    category: 'Farmacia',
    group: 'SEGUNDO',
    questions: [
      {
        id: '1',
        text: '¿Qué es un agonista en farmacología?',
        options: [
          'Una sustancia que activa un receptor para producir una respuesta',
          'Una sustancia que bloquea un receptor',
          'Un medicamento con alta toxicidad',
          'Un tipo de enzima digestiva',
        ],
        correctAnswer: 0,
      },
      {
        id: '2',
        text: '¿Qué es un antagonista competitivo?',
        options: [
          'Un fármaco que compite con el agonista por el mismo receptor',
          'Un fármaco que se une a un sitio diferente del receptor',
          'Un fármaco que potencia el efecto del agonista',
          'Un inhibidor irreversible',
        ],
        correctAnswer: 0,
      },
      {
        id: '3',
        text: '¿Qué significa DL50 en toxicología?',
        options: [
          'Dosis letal media que mata al 50% de una población',
          'Dosis efectiva en el 50% de la población',
          'Duración del efecto de 50 minutos',
          'Dosis mínima requerida para efecto terapéutico',
        ],
        correctAnswer: 0,
      },
      {
        id: '4',
        text: '¿Qué es la tolerancia farmacológica?',
        options: [
          'Disminución de la respuesta a un fármaco tras su uso continuado',
          'Aumento de la sensibilidad a un fármaco',
          'Reacción alérgica a un medicamento',
          'Efecto secundario leve',
        ],
        correctAnswer: 0,
      },
      {
        id: '5',
        text: '¿Qué es la ventana terapéutica?',
        options: [
          'Rango de dosis entre la efectiva y la tóxica',
          'Tiempo que dura el efecto del fármaco',
          'Periodo entre tomas de medicamento',
          'Momento del día óptimo para administrar el fármaco',
        ],
        correctAnswer: 0,
      },
      {
        id: '6',
        text: '¿Qué son los fármacos de margen terapéutico estrecho?',
        options: [
          'Aquellos cuya dosis terapéutica está muy cercana a la tóxica',
          'Medicamentos de dosis única',
          'Fármacos con alta biodisponibilidad',
          'Medicamentos de venta libre',
        ],
        correctAnswer: 0,
      },
      {
        id: '7',
        text: '¿Qué es una interacción farmacocinética?',
        options: [
          'Cuando un fármaco afecta la absorción, distribución, metabolismo o excreción de otro',
          'Cuando dos fármacos tienen el mismo mecanismo de acción',
          'Cuando un fármaco bloquea el receptor de otro',
          'Una reacción alérgica entre dos medicamentos',
        ],
        correctAnswer: 0,
      },
      {
        id: '8',
        text: '¿Qué órgano es principalmente responsable del metabolismo de los fármacos?',
        options: [
          'El hígado',
          'Los riñones',
          'El corazón',
          'Los pulmones',
        ],
        correctAnswer: 0,
      },
      {
        id: '9',
        text: '¿Qué significa "vía de administración parenteral"?',
        options: [
          'Administración que evita el tracto gastrointestinal',
          'Administración oral',
          'Aplicación tópica',
          'Ingesta de alimentos con el fármaco',
        ],
        correctAnswer: 0,
      },
      {
        id: '10',
        text: '¿Qué es el efecto de primer paso hepático?',
        options: [
          'La metabolización inicial de un fármaco en el hígado antes de llegar a la circulación sistémica',
          'La primera dosis administrada de un medicamento',
          'La eliminación del fármaco por los riñones',
          'La absorción del fármaco en el intestino',
        ],
        correctAnswer: 0,
      },
    ],
    createdAt: new Date('2024-03-16'),
  },
  {
    id: '8',
    title: 'Tecnología Farmacéutica',
    category: 'Farmacia',
    group: 'TERCERO',
    questions: [
      {
        id: '1',
        text: '¿Qué es la liofilización?',
        options: [
          'Un método de secado por congelación y sublimación',
          'Un proceso de esterilización por calor',
          'Una técnica de mezclado de polvos',
          'Un tipo de recubrimiento de tabletas',
        ],
        correctAnswer: 0,
      },
      {
        id: '2',
        text: '¿Qué es una emulsión?',
        options: [
          'Una mezcla de dos líquidos no miscibles',
          'Una solución sólida',
          'Un gas disuelto en líquido',
          'Una suspensión de sólidos en gas',
        ],
        correctAnswer: 0,
      },
      {
        id: '3',
        text: '¿Cuál es el propósito de un agente desintegrante en una tableta?',
        options: [
          'Facilitar la ruptura de la tableta en el tracto gastrointestinal',
          'Darle color a la tableta',
          'Mejorar el sabor',
          'Prolongar la vida útil',
        ],
        correctAnswer: 0,
      },
      {
        id: '4',
        text: '¿Qué es una cápsula de liberación prolongada?',
        options: [
          'Una cápsula diseñada para liberar el fármaco lentamente',
          'Una cápsula que se disuelve inmediatamente',
          'Una cápsula para administración intravenosa',
          'Una cápsula que contiene una sola dosis',
        ],
        correctAnswer: 0,
      },
      {
        id: '5',
        text: '¿Qué significa GMP en la industria farmacéutica?',
        options: [
          'Buenas Prácticas de Manufactura',
          'Gestión de Productos Médicos',
          'Garantía de Medicamentos y Productos',
          'Guía de Métodos de Producción',
        ],
        correctAnswer: 0,
      },
      {
        id: '6',
        text: '¿Cuál es el objetivo de la recubierta entérica en tabletas?',
        options: [
          'Proteger el fármaco de la degradación ácida en el estómago',
          'Mejorar el sabor del medicamento',
          'Hacer que la tableta sea más atractiva visualmente',
          'Aumentar la velocidad de disolución en el estómago',
        ],
        correctAnswer: 0,
      },
      {
        id: '7',
        text: '¿Qué es un sistema transdérmico de liberación de fármacos?',
        options: [
          'Un parche que administra el medicamento a través de la piel',
          'Una inyección subcutánea',
          'Un aerosol nasal',
          'Una crema tópica para aplicación local',
        ],
        correctAnswer: 0,
      },
      {
        id: '8',
        text: '¿Qué función tiene un conservante en una formulación farmacéutica?',
        options: [
          'Prevenir el crecimiento microbiano',
          'Dar color al producto',
          'Actuar como principio activo',
          'Aumentar la viscosidad',
        ],
        correctAnswer: 0,
      },
      {
        id: '9',
        text: '¿Qué es la biodisponibilidad relativa?',
        options: [
          'Comparación de la biodisponibilidad de dos formulaciones distintas del mismo fármaco',
          'La cantidad total de fármaco administrado',
          'La biodisponibilidad en diferentes especies animales',
          'La biodisponibilidad de un fármaco comparado con otro diferente',
        ],
        correctAnswer: 0,
      },
      {
        id: '10',
        text: '¿Qué es la granulación en húmedo en la fabricación de tabletas?',
        options: [
          'Un proceso donde los polvos se agregan usando un líquido aglutinante',
          'Una técnica de compresión directa',
          'Un método de secado de polvos',
          'Un tipo de recubrimiento de tabletas',
        ],
        correctAnswer: 0,
      },
    ],
    createdAt: new Date('2024-03-17'),
  },
  // Exámenes de Matemáticas para PRIMERO, SEGUNDO, TERCERO y CUARTO
  {
    id: '9',
    title: 'Álgebra Básica',
    category: 'Matemáticas',
    group: 'PRIMERO',
    questions: [
      {
        id: '1',
        text: '¿Cuál es la solución de la ecuación 2x + 5 = 15?',
        options: ['x = 5', 'x = 10', 'x = -5', 'x = 2'],
        correctAnswer: 0,
      },
      {
        id: '2',
        text: '¿Qué representa la pendiente en una ecuación lineal?',
        options: [
          'La tasa de cambio entre dos variables',
          'El punto donde la línea cruza el eje Y',
          'El valor de X cuando Y es cero',
          'La intersección con el eje X',
        ],
        correctAnswer: 0,
      },
      {
        id: '3',
        text: 'Simplifica la expresión: (3x^2)(2x^3)',
        options: ['6x^5', '5x^6', '6x^6', '5x^5'],
        correctAnswer: 0,
      },
      {
        id: '4',
        text: '¿Cuál es el valor de x en la ecuación x/4 = 3?',
        options: ['x = 12', 'x = 7', 'x = 1', 'x = -12'],
        correctAnswer: 0,
      },
      {
        id: '5',
        text: 'Factoriza la expresión: x^2 - 9',
        options: [
          '(x + 3)(x - 3)',
          '(x - 9)(x + 1)',
          '(x + 9)(x - 1)',
          '(x + 9)(x + 1)',
        ],
        correctAnswer: 0,
      },
      {
        id: '6',
        text: 'Resuelve para x: 5x - 2 = 3x + 6',
        options: ['x = 4', 'x = -4', 'x = 2', 'x = -2'],
        correctAnswer: 0,
      },
      {
        id: '7',
        text: '¿Cuál es la fórmula del área de un rectángulo?',
        options: [
          'Área = base x altura',
          'Área = base + altura',
          'Área = (base x altura)/2',
          'Área = 2(base + altura)',
        ],
        correctAnswer: 0,
      },
      {
        id: '8',
        text: 'Simplifica la expresión: 4(x - 2) + 3',
        options: ['4x - 5', '4x + 5', '4x - 11', '4x + 11'],
        correctAnswer: 0,
      },
      {
        id: '9',
        text: 'Calcula el valor numérico de 2x + y cuando x = 3 e y = -1',
        options: ['5', '7', '1', '-5'],
        correctAnswer: 0,
      },
      {
        id: '10',
        text: '¿Cuál es el resultado de dividir 0 entre cualquier número distinto de cero?',
        options: ['0', 'Indefinido', 'El número mismo', 'Infinito'],
        correctAnswer: 0,
      },
    ],
    createdAt: new Date('2024-03-18'),
  },
  {
    id: '10',
    title: 'Cálculo Diferencial',
    category: 'Matemáticas',
    group: 'SEGUNDO',
    questions: [
      {
        id: '1',
        text: '¿Cuál es la derivada de f(x) = x^2?',
        options: ['f\'(x) = 2x', 'f\'(x) = x', 'f\'(x) = x^2', 'f\'(x) = 0'],
        correctAnswer: 0,
      },
      {
        id: '2',
        text: '¿Qué representa la derivada de una función en un punto?',
        options: [
          'La pendiente de la tangente en ese punto',
          'El área bajo la curva',
          'El valor máximo de la función',
          'El punto de inflexión',
        ],
        correctAnswer: 0,
      },
      {
        id: '3',
        text: 'Si f(x) = sin(x), ¿cuál es f\'(x)?',
        options: [
          'f\'(x) = cos(x)',
          'f\'(x) = -sin(x)',
          'f\'(x) = -cos(x)',
          'f\'(x) = tan(x)',
        ],
        correctAnswer: 0,
      },
      {
        id: '4',
        text: '¿Cuál es la derivada de f(x) = e^x?',
        options: ['f\'(x) = e^x', 'f\'(x) = x e^x', 'f\'(x) = e^x + x', 'f\'(x) = e^{x-1}'],
        correctAnswer: 0,
      },
      {
        id: '5',
        text: 'Si y = ln(x), entonces dy/dx es igual a:',
        options: [
          '1/x',
          'ln(x)',
          'x',
          'e^x',
        ],
        correctAnswer: 0,
      },
      {
        id: '6',
        text: '¿Qué regla se utiliza para derivar el producto de dos funciones?',
        options: [
          'Regla del producto',
          'Regla de la cadena',
          'Regla del cociente',
          'Regla de L’Hôpital',
        ],
        correctAnswer: 0,
      },
      {
        id: '7',
        text: '¿Cuál es la derivada de f(x) = 1/x?',
        options: [
          'f\'(x) = -1/x^2',
          'f\'(x) = 1/x^2',
          'f\'(x) = x',
          'f\'(x) = -x',
        ],
        correctAnswer: 0,
      },
      {
        id: '8',
        text: 'Si f(x) = x^3, ¿cuál es la segunda derivada f\'\'(x)?',
        options: ['f\'\'(x) = 6x', 'f\'\'(x) = 3x^2', 'f\'\'(x) = 2x', 'f\'\'(x) = 0'],
        correctAnswer: 0,
      },
      {
        id: '9',
        text: '¿Qué indica un punto crítico en el análisis de una función?',
        options: [
          'Un posible máximo o mínimo',
          'Un punto de discontinuidad',
          'Un valor asintótico',
          'Una raíz de la función',
        ],
        correctAnswer: 0,
      },
      {
        id: '10',
        text: '¿Cuál es la derivada de f(x) = cos(x)?',
        options: [
          'f\'(x) = -sin(x)',
          'f\'(x) = sin(x)',
          'f\'(x) = cos(x)',
          'f\'(x) = -cos(x)',
        ],
        correctAnswer: 0,
      },
    ],
    createdAt: new Date('2024-03-19'),
  },
  {
    id: '11',
    title: 'Estadística y Probabilidad',
    category: 'Matemáticas',
    group: 'TERCERO',
    questions: [
      {
        id: '1',
        text: '¿Qué mide la media aritmética de un conjunto de datos?',
        options: [
          'El promedio de los valores',
          'El valor más frecuente',
          'El valor central',
          'La dispersión de los datos',
        ],
        correctAnswer: 0,
      },
      {
        id: '2',
        text: '¿Cuál es la probabilidad de obtener cara al lanzar una moneda equilibrada?',
        options: ['0.5', '0.25', '1', '0'],
        correctAnswer: 0,
      },
      {
        id: '3',
        text: '¿Qué representa la desviación estándar en estadística?',
        options: [
          'La dispersión de los datos respecto a la media',
          'El valor máximo del conjunto',
          'El rango entre el mayor y menor valor',
          'La suma de todos los datos',
        ],
        correctAnswer: 0,
      },
      {
        id: '4',
        text: '¿Qué es una variable aleatoria discreta?',
        options: [
          'Una variable que puede tomar valores contables',
          'Una variable que puede tomar cualquier valor en un intervalo',
          'Una variable dependiente del tiempo',
          'Una constante',
        ],
        correctAnswer: 0,
      },
      {
        id: '5',
        text: 'En un dado justo de seis caras, ¿cuál es la probabilidad de sacar un número par?',
        options: ['0.5', '0.33', '0.66', '0.25'],
        correctAnswer: 0,
      },
      {
        id: '6',
        text: '¿Qué es el evento complementario en probabilidad?',
        options: [
          'El evento que representa todos los resultados que no son parte del evento original',
          'El evento que ocurre simultáneamente con otro',
          'El evento imposible',
          'El evento seguro',
        ],
        correctAnswer: 0,
      },
      {
        id: '7',
        text: '¿Qué es una distribución normal?',
        options: [
          'Una distribución de probabilidad con forma de campana simétrica',
          'Una distribución uniforme',
          'Una distribución sesgada a la derecha',
          'Una distribución discreta',
        ],
        correctAnswer: 0,
      },
      {
        id: '8',
        text: '¿Qué significa una correlación de 0 entre dos variables?',
        options: [
          'No hay relación lineal entre las variables',
          'Existe una relación lineal perfecta',
          'Las variables son inversamente proporcionales',
          'Las variables son dependientes',
        ],
        correctAnswer: 0,
      },
      {
        id: '9',
        text: 'Si la probabilidad de que llueva es 0.2, ¿cuál es la probabilidad de que no llueva?',
        options: ['0.8', '0.2', '1', '0'],
        correctAnswer: 0,
      },
      {
        id: '10',
        text: '¿Qué es una muestra en estadística?',
        options: [
          'Un subconjunto de la población utilizado para hacer inferencias',
          'El total de individuos o elementos bajo estudio',
          'Un valor extremo',
          'Una medición errónea',
        ],
        correctAnswer: 0,
      },
    ],
    createdAt: new Date('2024-03-20'),
  },
  {
    id: '12',
    title: 'Cálculo Integral y Ecuaciones Diferenciales',
    category: 'Matemáticas',
    group: 'CUARTO',
    questions: [
      {
        id: '1',
        text: '¿Qué representa la integral definida de una función entre dos puntos?',
        options: [
          'El área bajo la curva entre esos puntos',
          'La pendiente de la función',
          'El valor de la función en un punto',
          'La derivada de la función',
        ],
        correctAnswer: 0,
      },
      {
        id: '2',
        text: 'Si F(x) es la antiderivada de f(x) = 2x, ¿cuál es F(x)?',
        options: [
          'F(x) = x^2 + C',
          'F(x) = 2x^2 + C',
          'F(x) = ln(x) + C',
          'F(x) = e^{2x} + C',
        ],
        correctAnswer: 0,
      },
      {
        id: '3',
        text: '¿Cuál es la integral de f(x) = e^x?',
        options: [
          '∫e^x dx = e^x + C',
          '∫e^x dx = x e^x + C',
          '∫e^x dx = e^{x+1} + C',
          '∫e^x dx = ln(e^x) + C',
        ],
        correctAnswer: 0,
      },
      {
        id: '4',
        text: '¿Qué es una ecuación diferencial ordinaria?',
        options: [
          'Una ecuación que relaciona una función con sus derivadas',
          'Una ecuación algebraica simple',
          'Una ecuación que involucra derivadas parciales',
          'Una ecuación sin variables dependientes',
        ],
        correctAnswer: 0,
      },
      {
        id: '5',
        text: '¿Cuál es la solución general de la ecuación diferencial dy/dx = ky?',
        options: [
          'y = Ce^{kx}',
          'y = kx + C',
          'y = C e^{-kx}',
          'y = C x^k',
        ],
        correctAnswer: 0,
      },
      {
        id: '6',
        text: '¿Qué método se utiliza para resolver ecuaciones diferenciales lineales de primer orden?',
        options: [
          'Factor integrante',
          'Método de separación de variables',
          'Series de Taylor',
          'Transformada de Laplace',
        ],
        correctAnswer: 0,
      },
      {
        id: '7',
        text: '¿Qué representa la constante de integración C en una integral indefinida?',
        options: [
          'La familia de todas las antiderivadas posibles',
          'El valor exacto de la integral',
          'El límite inferior de integración',
          'El área bajo la curva',
        ],
        correctAnswer: 0,
      },
      {
        id: '8',
        text: 'Si ∫x dx = (1/2)x^2 + C, ¿cuál es la integral definida de x desde 0 hasta 2?',
        options: ['2', '4', '0', '1'],
        correctAnswer: 0,
      },
      {
        id: '9',
        text: '¿Qué es una integral impropia?',
        options: [
          'Una integral con límites infinitos o integrando funciones no acotadas',
          'Una integral que no se puede resolver',
          'Una integral definida entre dos puntos finitos',
          'Una integral que resulta en un número negativo',
        ],
        correctAnswer: 0,
      },
      {
        id: '10',
        text: '¿Qué método se utiliza para resolver una ecuación diferencial de variables separables?',
        options: [
          'Separar y luego integrar ambos lados',
          'Aplicar derivadas parciales',
          'Usar series de Fourier',
          'Método de Euler',
        ],
        correctAnswer: 0,
      },
    ],
    createdAt: new Date('2024-03-21'),
  },
];
